name: kubernetes

on:
  workflow_call:

jobs:

  EKS:
    runs-on: ubuntu-latest  
    if: github.ref == 'refs/heads/develop'
    steps:
      - uses: actions/checkout@v3      
      - name: configurando credenciais da AWS
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.ID_CHAVE_ACESSO }}
          aws-secret-access-key: ${{ secrets.CHAVE_SECRETA }}
          aws-region: us-east-1
          
          
      - run: git clone https://github.com/danielcorreaa/tech-challenge-infra-terraform-kubernetes.git

      - name: HashiCorp - Setup Terraform
        uses: hashicorp/setup-terraform@v2.0.3
        
      - run: terraform -chdir=tech-challenge-infra-terraform-kubernetes/env/develop init
     
      - run: terraform -chdir=tech-challenge-infra-terraform-kubernetes/env/develop apply -auto-approve  

      - name: Kubectl tool installer
        uses: Azure/setup-kubectl@v3
      
      - run: aws sts get-caller-identity
    
      - run: aws eks update-kubeconfig --region us-west-2 --name dev
    
      - run: kubectl get svc

      - run: kubectl delete secret MYSQL_DATABASE --ignore-not-found
      - run: kubectl create secret generic MYSQL_DATABASE --from-literal=.MYSQL_DATABASE=${{secrets.MYSQL_DATABASE}}

      - run: kubectl delete secret MYSQL_USER --ignore-not-found
      - run: kubectl create secret generic MYSQL_USER --from-literal=.MYSQL_USER=${{secrets.MYSQL_USER}}
      
      - run: kubectl delete secret MYSQL_PASSWORD --ignore-not-found
      - run: kubectl create secret generic MYSQL_PASSWORD --from-literal=.MYSQL_PASSWORD=${{secrets.MYSQL_PASSWORD}}

      - run: kubectl delete secret DB_PASSWORD --ignore-not-found
      - run: kubectl create secret generic DB_PASSWORD --from-literal=.DB_PASSWORD=${{secrets.MYSQL_PASSWORD}}

      - run: kubectl delete secret DB_NAME --ignore-not-found
      - run: kubectl create secret generic DB_NAME --from-literal=.DB_NAME=${{secrets.MYSQL_DATABASE}}

      - run: kubectl delete secret DB_USERNAME --ignore-not-found
      - run: kubectl create secret generic DB_USERNAME --from-literal=.DB_USERNAME=${{secrets.MYSQL_USER}}
      
      - run: kubectl apply -f terraform -tech-challenge-infra-terraform-kubernetes/kubernates/mysql/mysql-configmap.yaml.yaml 
      - run: kubectl apply -f terraform -tech-challenge-infra-terraform-kubernetes/kubernates/mysql/mysql-pv.yaml.yaml 
      - run: kubectl apply -f terraform -tech-challenge-infra-terraform-kubernetes/kubernates/mysql/mysql-deployment-service.yaml 
      - run: kubectl apply -f terraform -tech-challenge-infra-terraform-kubernetes/kubernates/mysql/mysql-deployment.yaml 

      - run: kubectl apply -f terraform -tech-challenge-infra-terraform-kubernetes/kubernates/java/app-tech-challenge-service.yaml 
      - run: kubectl apply -f terraform -tech-challenge-infra-terraform-kubernetes/kubernates/java/app-tech-challenge.yaml
